---
layout : post
title : 190922_TIL (Today I Learn)
tags : [TIL]
comments: true
---
### 오늘 한 일
- C++ 강의를 듣고 정리하였다.
  - Exception
  - Standard Exception

---
### 백지 노트
- C에서는 예외를 처리할 경우 return 값 만을 가지고 예외를 처리하도록 한다. 즉, 예외처리와 에러처리가 나뉘어 져있지 않다. 따라서, 사용자가 확인을 하지 않을 경우 예외에 대한 처리 없이 성공적으로 컴파일이 되는 것을 식별할 수 있다. 이는 당장에는 큰 문제가 없지만, ***잠재적 버그 유발*** 한다. 따라서, C++에서는 C와 달리 예외 처리와 return 행위를 나누어 구별한다.

- throw 라는 키워드를 이용할 경우, 사용자의 적절한 처리가 없을 때, 예외가 발생하게 된다.

- try catch문을 이용해서 예외를 전달받아 처리하도록 한다.
  - catch( ... ) 인자로 전달되는 것들을 받아서 처리할 수 있다. 앞의 내용과 같이, 가변인자를 활용하여 사용도 가능하다. 다만, 가변인자는 모든 인자를 전달받을 수 있기 때문에, 좀 더 narrow한 처리를 하는 행위를 무시하는 경우가 발생한다. 즉, catch(int a) 문장보다 catch(...) 문장을 앞에 쓸 경우 int처리가 아닌 다른 것으로 그냥 받아버릴 수도 있다. 컴파일러는 이를 방지하기 위해 가변인자를 ***마지막 작성*** 하라고 요구한다.

- 예외 처리같은경우 단순한 primary type을 이용해 전달하기 보다는, Class화 하여 전달할 때 진가를 발휘한다. class를 이용하게 된다면, 각종 상태를 포함해 함수로 헨들링할 수 있는 장점이 있다.
  - 보통 C++에서는 base 클래스를 제공해준다. 따라서, 예외 클래스를 만들기 위해서는 base 클래스를 상속받아 사용하면 된다.
    - #include <exception> => std::exception (base class name)

  - 예외를 catch문으로 전달받을 경우 보통 reference로 전달받는다.

  - C++ standard exception
    - std::bad_alloc
    - std::range_error

- 함수를 만들 때, 에외 유무를 표기해주는 것이 좋다.
  - C++98 이전에서는 throw라는 키워드를 함수 옆에 적어줌으로 표기했다.
  - throw (int) => 이 키워드를 함수 뒤에 적어준다면, "나는 int를 예외로 전달받아 처리하는 동작을 갖고 있는 함수다." 라는 것을 알려준다.
  - throw() 이렇게 적는다면, 나는 예외가 없다는 표시다.
  - 만약, 적지 않는다면 예외가 발생할수도 있다라는 표시이다.

- 시대가 흐르면서 점차 개발을 해보니.. 예외의 유무를 판단하는 것이 더 중요해졌다. 즉, 어떤 예외가 발생했냐보다는 존재 유무를 판단만하면 된다는 것이다.
  - noexcept 키워드
    - noexcept(false) -> 예외 있음
    - noexcpet(true)  -> 예외 없음
    - noexcept        -> 예외 없음 (except(ture)의 축약버전)

  - 이 키워드를 조사해서 무엇을 하나?
    1. 컴파일러에서 최적화 하는데 도움이 된다.
      - 컴파일러가 최적화 할 경우 예외가 없으면, 좀 더 최적화를 쉽게 할 수 있다.
    2. move 연산자에 활용
      - move 연산자 구현시, noexcept에 따라 구현이 완전히 달라짐.
